/**
 * opcode.c
 */

#include <stdint.h>
#include "opcode.h"

#define UNDEF_OPCODE {UNDEFINED_OP, UNDEFINED_MODE}

static const opcode_t opcodes[UINT8_MAX] = {
    /* 0x0X instructions */
    {BRK, IMPLICIT},
    {ORA, INDEXED_INDIRECT},
    UNDEF_OPCODE,
    UNDEF_OPCODE,
    UNDEF_OPCODE,
    {ORA, ZERO_PAGE},
    {ASL, ZERO_PAGE},
    UNDEF_OPCODE,
    {PHP, IMPLICIT},
    {ORA, IMMEDIATE},
    {ASL, ACCUMULATOR},
    UNDEF_OPCODE,
    UNDEF_OPCODE,
    {ORA, ABSOLUTE},
    {ASL, ABSOLUTE},
    UNDEF_OPCODE,

    /* 0x1X instructions */
    {BPL, RELATIVE},
    {ORA, INDIRECT_INDEXED},
    UNDEF_OPCODE,
    UNDEF_OPCODE,
    UNDEF_OPCODE,
    {ORA, ZERO_PAGE_X},
    {ASL, ZERO_PAGE_X},
    UNDEF_OPCODE,
    {CLC, IMPLICIT},
    {ORA, ABSOLUTE_Y},
    UNDEF_OPCODE,
    UNDEF_OPCODE,
    UNDEF_OPCODE,
    {ORA, ABSOLUTE_X},
    {ASL, ABSOLUTE_X},
    UNDEF_OPCODE,

    /* 0x2X instructions */
    {JSR, ABSOLUTE},
    {AND, INDEXED_INDIRECT},
    UNDEF_OPCODE,
    UNDEF_OPCODE,
    {BIT, ZERO_PAGE},
    {AND, ZERO_PAGE},
    {ROL, ZERO_PAGE},
    UNDEF_OPCODE,
    {PLP, IMPLICIT},
    {AND, IMMEDIATE},
    {ROL, ACCUMULATOR},
    UNDEF_OPCODE,
    {BIT, ABSOLUTE},
    {AND, ABSOLUTE},
    {ROL, ABSOLUTE},
    UNDEF_OPCODE,

    /* 0x3X instructions */
    {BMI, RELATIVE},
    {AND, INDIRECT_INDEXED},
    UNDEF_OPCODE,
    UNDEF_OPCODE,
    UNDEF_OPCODE,
    {AND, ZERO_PAGE_X},
    {ROL, ZERO_PAGE_X},
    UNDEF_OPCODE,
    {SEC, IMPLICIT},
    {AND, ABSOLUTE_Y},
    UNDEF_OPCODE,
    UNDEF_OPCODE,
    UNDEF_OPCODE,
    {AND, ABSOLUTE_X},
    {ROL, ABSOLUTE_X},
    UNDEF_OPCODE,

    /* 0x4X instructions */
    {RTI, IMPLICIT},
    {EOR, INDEXED_INDIRECT},
    UNDEF_OPCODE,
    UNDEF_OPCODE,
    UNDEF_OPCODE,
    {EOR, ZERO_PAGE},
    {LSR, ZERO_PAGE},
    UNDEF_OPCODE,
    {PHA, IMPLICIT},
    {EOR, IMMEDIATE},
    {LSR, ACCUMULATOR},
    UNDEF_OPCODE,
    {JMP, ABSOLUTE},
    {EOR, ABSOLUTE},
    {LSR, ABSOLUTE},
    UNDEF_OPCODE,

    /* 0x5X instructions */
    {BVC, RELATIVE},
    {EOR, INDIRECT_INDEXED},
    UNDEF_OPCODE,
    UNDEF_OPCODE,
    UNDEF_OPCODE,
    {EOR, ZERO_PAGE_X},
    {LSR, ZERO_PAGE_X},
    UNDEF_OPCODE,
    {CLI, IMPLICIT},
    {EOR, ABSOLUTE_Y},
    UNDEF_OPCODE,
    UNDEF_OPCODE,
    UNDEF_OPCODE,
    {EOR, ABSOLUTE_X},
    {LSR, ABSOLUTE_X},
    UNDEF_OPCODE,

    /* 0x6X instructions */
    {RTS, IMPLICIT},
    {ADC, INDEXED_INDIRECT},
    UNDEF_OPCODE,
    UNDEF_OPCODE,
    UNDEF_OPCODE,
    {ADC, ZERO_PAGE},
    {ROR, ZERO_PAGE},
    UNDEF_OPCODE,
    {PLA, IMPLICIT},
    {ADC, IMMEDIATE},
    {ROR, ACCUMULATOR},
    UNDEF_OPCODE,
    {JMP, INDIRECT},
    {ADC, ABSOLUTE},
    {ROR, ABSOLUTE},
    UNDEF_OPCODE,

    /* 0x7X instructions */
    {BVS, RELATIVE},
    {ADC, INDIRECT_INDEXED},
    UNDEF_OPCODE,
    UNDEF_OPCODE,
    UNDEF_OPCODE,
    {ADC, ZERO_PAGE_X},
    {ROR, ZERO_PAGE_X},
    UNDEF_OPCODE,
    {SEI, IMPLICIT},
    {ADC, ABSOLUTE_Y},
    UNDEF_OPCODE,
    UNDEF_OPCODE,
    UNDEF_OPCODE,
    {ADC, ABSOLUTE_X},
    {ROR, ABSOLUTE_X},
    UNDEF_OPCODE,

    /* 0x8A instructions */
    UNDEF_OPCODE,
    {STA, INDEXED_INDIRECT},
    UNDEF_OPCODE,
    UNDEF_OPCODE,
    {STY, ZERO_PAGE},
    {STA, ZERO_PAGE},
    {STX, ZERO_PAGE},
    UNDEF_OPCODE,
    {DEY, IMPLICIT},
    UNDEF_OPCODE,
    {TXA, IMPLICIT},
    UNDEF_OPCODE,
    {STY, ABSOLUTE},
    {STA, ABSOLUTE},
    {STX, ABSOLUTE},
    UNDEF_OPCODE,

    /* 0x9A instructions */
    {BCC, RELATIVE},
    {STA, INDIRECT_INDEXED},
    UNDEF_OPCODE,
    UNDEF_OPCODE,
    {STY, ZERO_PAGE_X},
    {STA, ZERO_PAGE_X},
    {STX, ZERO_PAGE_Y},
    UNDEF_OPCODE,
    {TYA, IMPLICIT},
    {STA, ABSOLUTE_Y},
    {TXS, IMPLICIT},
    UNDEF_OPCODE,
    UNDEF_OPCODE,
    {STA, ABSOLUTE_X},
    UNDEF_OPCODE,
    UNDEF_OPCODE,

    /* 0xAX instructions */
    {LDY, IMMEDIATE},
    {LDA, INDEXED_INDIRECT},
    {LDX, IMMEDIATE},
    UNDEF_OPCODE,
    {LDY, ZERO_PAGE},
    {LDA, ZERO_PAGE},
    {LDX, ZERO_PAGE},
    UNDEF_OPCODE,
    {TAY, IMPLICIT},
    {LDA, IMMEDIATE},
    {TAX, IMPLICIT},
    UNDEF_OPCODE,
    {LDY, ABSOLUTE},
    {LDA, ABSOLUTE},
    {LDX, ABSOLUTE},
    UNDEF_OPCODE,

    /* 0xBX instructions */
    {BCS, RELATIVE},
    {LDA, INDIRECT_INDEXED},
    UNDEF_OPCODE,
    UNDEF_OPCODE,
    {LDY, ZERO_PAGE_X},
    {LDA, ZERO_PAGE_X},
    {LDX, ZERO_PAGE_Y},
    UNDEF_OPCODE,
    {CLV, IMPLICIT},
    {LDA, ABSOLUTE_Y},
    {TSX, IMPLICIT},
    UNDEF_OPCODE,
    {LDY, ABSOLUTE_X},
    {LDA, ABSOLUTE_X},
    {LDX, ABSOLUTE_Y},
    UNDEF_OPCODE,

    /* 0xCX instructions */
    {CPY, IMMEDIATE},
    {CMP, INDEXED_INDIRECT},
    UNDEF_OPCODE,
    UNDEF_OPCODE,
    {CPY, ZERO_PAGE},
    {CMP, ZERO_PAGE},
    {DEC, ZERO_PAGE},
    UNDEF_OPCODE,
    {INY, IMPLICIT},
    {CMP, IMMEDIATE},
    {DEX, IMPLICIT},
    UNDEF_OPCODE,
    {CPY, ABSOLUTE},
    {CMP, ABSOLUTE},
    {DEC, ABSOLUTE},
    UNDEF_OPCODE,

    /* 0xDX instructions */
    {BNE, RELATIVE},
    {CMP, INDIRECT_INDEXED},
    UNDEF_OPCODE,
    UNDEF_OPCODE,
    UNDEF_OPCODE,
    {CMP, ZERO_PAGE_X},
    {DEC, ZERO_PAGE_X},
    UNDEF_OPCODE,
    {CLD, IMPLICIT},
    {CMP, ABSOLUTE_Y},
    UNDEF_OPCODE,
    UNDEF_OPCODE,
    UNDEF_OPCODE,
    {CMP, ABSOLUTE_X},
    {DEC, ABSOLUTE_X},
    UNDEF_OPCODE,

    /* 0xEX instructions */
    {CPX, IMMEDIATE},
    {SBC, INDEXED_INDIRECT},
    UNDEF_OPCODE,
    UNDEF_OPCODE,
    {CPX, ZERO_PAGE},
    {SBC, ZERO_PAGE},
    {INC, ZERO_PAGE},
    UNDEF_OPCODE,
    {INX, IMPLICIT},
    {SBC, IMMEDIATE},
    {NOP, IMPLICIT},
    UNDEF_OPCODE,
    {CPX, ABSOLUTE},
    {SBC, ABSOLUTE},
    {INC, ABSOLUTE},
    UNDEF_OPCODE,

    /* 0xFX instructions */
    {BEQ, RELATIVE},
    {SBC, INDIRECT_INDEXED},
    UNDEF_OPCODE,
    UNDEF_OPCODE,
    UNDEF_OPCODE,
    {SBC, ZERO_PAGE_X},
    {INC, ZERO_PAGE_X},
    UNDEF_OPCODE,
    {SED, IMPLICIT},
    {SBC, ABSOLUTE_Y},
    UNDEF_OPCODE,
    UNDEF_OPCODE,
    UNDEF_OPCODE,
    {SBC, ABSOLUTE_X},
    {INC, ABSOLUTE_X},
};

char opcode_names[OPCODE_SIZE][4] = {"", "adc", "and", "asl", "bcc", "bcs", "beq", "bit",
                                     "bmi", "bne", "bpl", "brk", "bvc", "bvs", "clc",
                                     "cld", "cli", "clv", "cmp", "cpx", "cpy", "dec",
                                     "dex", "dey", "eor", "inc", "inx", "iny", "jmp",
                                     "jsr", "lda", "ldx", "ldy", "lsr", "nop", "ora",
                                     "pha", "php", "pla", "plp", "rol", "ror", "rti",
                                     "rts", "sbc", "sec", "sed", "sei", "sta", "stx",
                                     "sty", "tax", "tay", "tsx", "txa", "txs", "tya"};

const opcode_t*
decode_opcode (const uint8_t* byte)
{
  return opcodes + *byte;
}

const char*
get_opcode_name (const opcode_t* opcode)
{
  return opcode_names[opcode->code];
}
